const fs = require('fs');
const existing = require('/home/user/pollamundial2026/pollaworld-2026/server/src/db/squads.json');

const groups = {
  "A": ["República Checa", "México", "Sudáfrica", "Corea del Sur"],
  "B": ["Bosnia y Herzegovina", "Canadá", "Catar", "Suiza"],
  "C": ["Brasil", "Haití", "Marruecos", "Escocia"],
  "D": ["Australia", "Paraguay", "Turquía", "Estados Unidos"],
  "E": ["Curazao", "Ecuador", "Alemania", "Costa de Marfil"],
  "F": ["Japón", "Países Bajos", "Suecia", "Túnez"],
  "G": ["Bélgica", "Egipto", "Irán", "Nueva Zelanda"],
  "H": ["Cabo Verde", "Arabia Saudita", "España", "Uruguay"],
  "I": ["Francia", "Irak", "Noruega", "Senegal"],
  "J": ["Argelia", "Argentina", "Austria", "Jordania"],
  "K": ["Colombia", "RD Congo", "Portugal", "Uzbekistán"],
  "L": ["Croacia", "Inglaterra", "Ghana", "Panamá"]
};

const coaches = {
  "Bosnia y Herzegovina": "Sergej Barbarez", "Canadá": "Jesse Marsch", "Catar": "Tintín Márquez",
  "Suiza": "Murat Yakin", "Brasil": "Dorival Júnior", "Haití": "Sébastien Migné",
  "Marruecos": "Walid Regragui", "Escocia": "Steve Clarke", "Australia": "Tony Popovic",
  "Paraguay": "Gustavo Alfaro", "Turquía": "Vincenzo Montella", "Estados Unidos": "Mauricio Pochettino",
  "Curazao": "Dick Advocaat", "Ecuador": "Sebastián Beccacece", "Alemania": "Julian Nagelsmann",
  "Costa de Marfil": "Emerse Faé", "Japón": "Hajime Moriyasu", "Países Bajos": "Ronald Koeman",
  "Suecia": "Jon Dahl Tomasson", "Túnez": "Sami Trabelsi", "Bélgica": "Rudi Garcia",
  "Egipto": "Hossam Hassan", "Irán": "Amir Ghalenoei", "Nueva Zelanda": "Darren Bazeley",
  "Cabo Verde": "Bubista", "Arabia Saudita": "Hervé Renard", "España": "Luis de la Fuente",
  "Uruguay": "Marcelo Bielsa", "Francia": "Didier Deschamps", "Irak": "Jesús Casas",
  "Noruega": "Ståle Solbakken", "Senegal": "Pape Thiaw", "Argelia": "Vladimir Petković",
  "Argentina": "Lionel Scaloni", "Austria": "Ralf Rangnick", "Jordania": "Jamal Sellami",
  "Colombia": "Néstor Lorenzo", "RD Congo": "Sébastien Desabre", "Portugal": "Roberto Martínez",
  "Uzbekistán": "Srečko Katanec", "Croacia": "Zlatko Dalić", "Inglaterra": "Thomas Tuchel",
  "Ghana": "Otto Addo", "Panamá": "Thomas Christiansen"
};

function normalizePlayers(raw) {
  const gkNums = [1, 16, 23];
  const dfNums = [2, 3, 4, 5, 6, 7, 8, 9];
  const mfNums = [10, 11, 12, 13, 14, 15, 17, 18];
  const fwNums = [19, 20, 21, 22, 24, 25, 26];
  const players = [];
  raw.gk.forEach((p, i) => players.push({name: p.n, num: gkNums[i], pos: "GK", club: p.c, age: p.a||27, caps: p.ca||30}));
  raw.df.forEach((p, i) => players.push({name: p.n, num: dfNums[i], pos: "DF", club: p.c, age: p.a||27, caps: p.ca||30}));
  raw.mf.forEach((p, i) => players.push({name: p.n, num: mfNums[i], pos: "MF", club: p.c, age: p.a||27, caps: p.ca||30}));
  raw.fw.forEach((p, i) => players.push({name: p.n, num: fwNums[i], pos: "FW", club: p.c, age: p.a||27, caps: p.ca||30}));
  return players;
}

const teamsData = {};

// B
teamsData["Bosnia y Herzegovina"] = {gk:[{n:"I. Šehić",c:"Tuzla City",a:31,ca:20},{n:"N. Vasilj",c:"St. Pauli",a:29,ca:5},{n:"E. Šehić",c:"Sarajevo",a:25,ca:3}],df:[{n:"A. Barišić",c:"Rangers",a:31,ca:30},{n:"D. Dedić",c:"RB Salzburg",a:24,ca:15},{n:"S. Kolašinac",c:"Atalanta",a:32,ca:60},{n:"N. Katić",c:"Zürich",a:32,ca:30},{n:"D. Hadžikadunić",c:"Malmö",a:27,ca:15},{n:"B. Mujakić",c:"Orenburg",a:26,ca:5},{n:"E. Bičakčić",c:"Orenburg",a:35,ca:35},{n:"T. Gojak",c:"Mura",a:26,ca:5}],mf:[{n:"A. Tahirović",c:"Brøndby",a:22,ca:3},{n:"B. Ramić",c:"Tuzla City",a:24,ca:2},{n:"M. Krpić",c:"Željezničar",a:26,ca:3},{n:"S. Huseinbašić",c:"Köln",a:27,ca:10},{n:"D. Prcić",c:"Lech Poznań",a:31,ca:30},{n:"A. Đelilović",c:"Konyaspor",a:26,ca:5},{n:"E. Hajradinović",c:"Kasımpaşa",a:32,ca:25},{n:"R. Bašić",c:"Orenburg",a:29,ca:15}],fw:[{n:"E. Džeko",c:"Fenerbahçe",a:39,ca:140},{n:"D. Varešanović",c:"Tuzla City",a:27,ca:5},{n:"A. Huseinović",c:"Sarajevo",a:26,ca:3},{n:"S. Šabić",c:"Željezničar",a:22,ca:2},{n:"A. Gazibegović",c:"Sturm Graz",a:24,ca:10},{n:"B. Tabaković",c:"Teplice",a:25,ca:8}]};
teamsData["Canadá"] = {gk:[{n:"M. Crépeau",c:"Portland",a:31,ca:20},{n:"D. St. Clair",c:"Minnesota",a:28,ca:15},{n:"T. McGill",c:"Middlesbrough",a:25,ca:3}],df:[{n:"A. Johnston",c:"Celtic",a:27,ca:50},{n:"D. Cornelius",c:"PAOK",a:27,ca:25},{n:"K. Miller",c:"Portland",a:27,ca:40},{n:"R. Laryea",c:"Toronto",a:30,ca:45},{n:"K. Waterman",c:"Montreal",a:28,ca:10},{n:"S. Zator",c:"Korona",a:27,ca:5},{n:"N. Sigur",c:"HFX Wanderers",a:23,ca:2},{n:"J. de Fougerolles",c:"Fulham",a:20,ca:3}],mf:[{n:"S. Eustáquio",c:"Porto",a:28,ca:45},{n:"I. Koné",c:"Marseille",a:22,ca:10},{n:"J. Osorio",c:"Toronto",a:33,ca:75},{n:"L. Fraser",c:"Málaga",a:26,ca:10},{n:"M. Choinière",c:"Montreal",a:26,ca:8},{n:"A. Paton",c:"HFX Wanderers",a:24,ca:2},{n:"T. Borges",c:"Vancouver",a:27,ca:5},{n:"C. Loturi",c:"Ross County",a:24,ca:3}],fw:[{n:"C. Larin",c:"Mallorca",a:30,ca:75},{n:"J. David",c:"Lille",a:25,ca:55},{n:"L. Cavallini",c:"Tijuana",a:32,ca:35},{n:"T. Buchanan",c:"Inter",a:26,ca:40},{n:"D. Oluwaseyi",c:"Minnesota",a:25,ca:8},{n:"J. Russell-Rowe",c:"Columbus",a:22,ca:5}]};
teamsData["Catar"] = {gk:[{n:"S. Al Sheeb",c:"Al Sadd",a:35,ca:90},{n:"M. Barsham",c:"Al Sadd",a:27,ca:30},{n:"Y. Hassan",c:"Al Gharafa",a:25,ca:10}],df:[{n:"P. Miguel",c:"Al Sadd",a:34,ca:90},{n:"T. Salman",c:"Al Sadd",a:28,ca:65},{n:"L. Mendes",c:"Al Wakrah",a:34,ca:60},{n:"B. Khoukhi",c:"Al Sadd",a:35,ca:115},{n:"H. Al-Hamawende",c:"Al Sadd",a:24,ca:15},{n:"M. Ayash",c:"Al Ahli",a:25,ca:10},{n:"A. Suhail",c:"Al Sadd",a:23,ca:5},{n:"I. Al-Abdullah",c:"Al Gharafa",a:25,ca:10}],mf:[{n:"J. Al-Haydos",c:"Al Sadd",a:35,ca:110},{n:"A. Afif",c:"Al Sadd",a:28,ca:110},{n:"M. Waad",c:"Al Sadd",a:30,ca:40},{n:"A. Madibo",c:"Al Duhail",a:31,ca:50},{n:"H. Al-Haydos",c:"Al Duhail",a:24,ca:5},{n:"A. Fadhel",c:"Al Wakrah",a:24,ca:2},{n:"N. Yasser",c:"Al Duhail",a:24,ca:3},{n:"K. Al-Rawi",c:"Al Duhail",a:27,ca:25}],fw:[{n:"A. Alaeeldin",c:"Al Duhail",a:34,ca:60},{n:"H. Ayman",c:"Al Duhail",a:23,ca:15},{n:"I. Mohammad",c:"Al Wakrah",a:25,ca:5},{n:"Y. Abdurisag",c:"Al Sadd",a:25,ca:10},{n:"M. Muntari",c:"Al Duhail",a:31,ca:30},{n:"O. Al-Rawi",c:"Al Rayyan",a:23,ca:8}]};
teamsData["Suiza"] = {gk:[{n:"Y. Sommer",c:"Inter",a:36,ca:95},{n:"G. Kobel",c:"Dortmund",a:27,ca:15},{n:"Y. Mvogo",c:"Lorient",a:30,ca:10}],df:[{n:"M. Akanji",c:"Man City",a:30,ca:70},{n:"N. Elvedi",c:"Gladbach",a:28,ca:55},{n:"R. Rodríguez",c:"Betis",a:32,ca:110},{n:"S. Widmer",c:"Mainz",a:32,ca:50},{n:"C. Ramos",c:"Colonia",a:20,ca:3},{n:"E. Comert",c:"Valladolid",a:28,ca:15},{n:"A. Omeragic",c:"Montpellier",a:23,ca:10},{n:"L. Hauuri",c:"Winterthur",a:24,ca:2}],mf:[{n:"G. Xhaka",c:"Bayer Leverkusen",a:32,ca:135},{n:"R. Freuler",c:"Bologna",a:33,ca:75},{n:"D. Zakaria",c:"Monaco",a:28,ca:55},{n:"M. Aebischer",c:"Bologna",a:28,ca:30},{n:"F. Rieder",c:"Augsburg",a:23,ca:5},{n:"A. Jashari",c:"Luzern",a:22,ca:3},{n:"P. Sohm",c:"Strasbourg",a:24,ca:2},{n:"K. Diakité",c:"Basel",a:24,ca:5}],fw:[{n:"X. Shaqiri",c:"Basel",a:33,ca:125},{n:"B. Embolo",c:"Monaco",a:28,ca:70},{n:"R. Vargas",c:"Sevilla",a:26,ca:50},{n:"D. Ndoye",c:"Bologna",a:24,ca:20},{n:"N. Okafor",c:"Napoli",a:25,ca:25},{n:"Z. Amdouni",c:"Benfica",a:24,ca:15}]};

// C
teamsData["Brasil"] = {gk:[{n:"A. Becker",c:"Liverpool",a:32,ca:70},{n:"Éderson",c:"Man City",a:31,ca:30},{n:"Bento",c:"Al Nassr",a:26,ca:10}],df:[{n:"Danilo",c:"Fluminense",a:34,ca:65},{n:"E. Militão",c:"Real Madrid",a:27,ca:40},{n:"Marquinhos",c:"PSG",a:31,ca:90},{n:"G. Arana",c:"Atlético-MG",a:28,ca:15},{n:"L. Ortiz",c:"Flamengo",a:28,ca:10},{n:"Wendell",c:"Porto",a:31,ca:10},{n:"L. Beraldo",c:"PSG",a:21,ca:5},{n:"Y. Couto",c:"Dortmund",a:23,ca:8}],mf:[{n:"Casemiro",c:"Man Utd",a:33,ca:80},{n:"Bruno G.",c:"Newcastle",a:27,ca:30},{n:"J. Paquetá",c:"West Ham",a:27,ca:50},{n:"Douglas L.",c:"Wolves",a:27,ca:20},{n:"André",c:"Fluminense",a:24,ca:10},{n:"R. Veiga",c:"Palmeiras",a:30,ca:15},{n:"Gerson",c:"Flamengo",a:28,ca:10},{n:"L. Henrique",c:"Botafogo",a:25,ca:5}],fw:[{n:"Vini Jr.",c:"Real Madrid",a:25,ca:40},{n:"Rodrygo",c:"Real Madrid",a:24,ca:30},{n:"Raphinha",c:"Barcelona",a:28,ca:35},{n:"Gabriel J.",c:"Arsenal",a:27,ca:25},{n:"Endrick",c:"Real Madrid",a:18,ca:10},{n:"E. Savinho",c:"Man City",a:21,ca:8}]};
teamsData["Haití"] = {gk:[{n:"J. Duverger",c:"Stade Beaucairois",a:31,ca:20},{n:"A. Pierre",c:"Dunkerque",a:32,ca:15},{n:"D. Destin",c:"Real Hope",a:24,ca:5}],df:[{n:"C. Jean",c:"Bordeaux",a:31,ca:40},{n:"R. Métellus",c:"Reims",a:32,ca:25},{n:"A. Aveska",c:"Real Hope",a:29,ca:10},{n:"M. Christian",c:"Neuchâtel Xamax",a:28,ca:15},{n:"J. Alexis",c:"Dijkot",a:25,ca:8},{n:"S. Désir",c:"Real Hope",a:25,ca:5},{n:"N. Fils-Aimé",c:"Tampico",a:24,ca:3},{n:"R. Alceus",c:"Tampico",a:26,ca:5}],mf:[{n:"B. Bazile",c:"Villefranche",a:30,ca:35},{n:"D. Maurice",c:"Brest",a:27,ca:15},{n:"P. Antoine",c:"Real Hope",a:30,ca:20},{n:"R. Pierrot",c:"Loudoun",a:25,ca:10},{n:"C. Hilaire",c:"Real Hope",a:22,ca:3},{n:"W. Guillaume",c:"Real Hope",a:22,ca:2},{n:"J. St-Jean",c:"Don Bosco",a:24,ca:3},{n:"S. Célestin",c:"Tempête",a:25,ca:2}],fw:[{n:"D. Jean",c:"CSKA Sofía",a:26,ca:15},{n:"F. Pierrot",c:"Maccabi Haifa",a:29,ca:25},{n:"R. Belmar",c:"Gibraltar Utd",a:26,ca:5},{n:"M. Cantave",c:"Calcio Lecco",a:28,ca:10},{n:"S. Lacroix",c:"Real Hope",a:24,ca:3},{n:"K. Azor",c:"Tempête",a:25,ca:2}]};
teamsData["Marruecos"] = {gk:[{n:"Y. Bono",c:"Al Hilal",a:34,ca:65},{n:"M. El Kajoui",c:"RS Berkane",a:36,ca:50},{n:"K. Ouahabi",c:"FUS Rabat",a:24,ca:3}],df:[{n:"A. Hakimi",c:"PSG",a:26,ca:85},{n:"N. Mazraoui",c:"Man Utd",a:27,ca:40},{n:"R. Saïss",c:"Al Sadd",a:35,ca:85},{n:"N. Aguerd",c:"Real Sociedad",a:29,ca:55},{n:"A. Harit",c:"Marseille",a:28,ca:25},{n:"J. Belamri",c:"Wydad",a:24,ca:5},{n:"M. Aboukhlal",c:"Toulouse",a:25,ca:25},{n:"C. El Ouahdi",c:"Genk",a:22,ca:5}],mf:[{n:"S. Amrabat",c:"Fenerbahçe",a:28,ca:60},{n:"A. Ounahi",c:"Panathinaikos",a:25,ca:35},{n:"B. El Khannous",c:"Leicester",a:21,ca:15},{n:"Y. Bougha",c:"FUS Rabat",a:24,ca:3},{n:"E. Richardson",c:"Floresta",a:23,ca:5},{n:"I. Saibari",c:"PSV",a:24,ca:10},{n:"O. Serrhat",c:"Wydad",a:22,ca:2},{n:"R. Moutar",c:"Göztepe",a:25,ca:5}],fw:[{n:"H. Ziyech",c:"Al Duhail",a:32,ca:65},{n:"A. En-Nesyri",c:"Fenerbahçe",a:28,ca:80},{n:"A. Adli",c:"Bordeaux",a:24,ca:5},{n:"W. Cheddira",c:"Espanyol",a:27,ca:15},{n:"E. Ben Seghir",c:"Monaco",a:21,ca:8},{n:"Y. Salhi",c:"RS Berkane",a:25,ca:3}]};
teamsData["Escocia"] = {gk:[{n:"A. Gunn",c:"Norwich",a:29,ca:15},{n:"C. Gordon",c:"Celtic",a:42,ca:80},{n:"L. Kelly",c:"Motherwell",a:29,ca:5}],df:[{n:"A. Robertson",c:"Liverpool",a:31,ca:80},{n:"K. Tierney",c:"Arsenal",a:28,ca:55},{n:"J. Hendry",c:"Al Ettifaq",a:30,ca:40},{n:"G. Hanley",c:"Birmingham",a:33,ca:60},{n:"R. Porteous",c:"Watford",a:26,ca:15},{n:"N. Patterson",c:"Everton",a:23,ca:10},{n:"A. Hickey",c:"Brentford",a:23,ca:8},{n:"J. Souttar",c:"Rangers",a:28,ca:10}],mf:[{n:"C. McGregor",c:"Celtic",a:32,ca:65},{n:"J. McGinn",c:"Aston Villa",a:30,ca:75},{n:"S. McTominay",c:"Napoli",a:28,ca:60},{n:"B. Gilmour",c:"Napoli",a:24,ca:35},{n:"R. Christie",c:"Bournemouth",a:29,ca:40},{n:"K. McLean",c:"Norwich",a:33,ca:45},{n:"L. Ferguson",c:"Bologna",a:25,ca:15},{n:"B. Doak",c:"Middlesbrough",a:19,ca:3}],fw:[{n:"C. Adams",c:"Torino",a:29,ca:35},{n:"J. Dykes",c:"QPR",a:31,ca:35},{n:"L. Shankland",c:"Hearts",a:29,ca:15},{n:"J. Forrest",c:"Celtic",a:33,ca:40},{n:"K. Nisbet",c:"Aberdeen",a:28,ca:10},{n:"T. Conway",c:"Middlesbrough",a:22,ca:5}]};

// D
teamsData["Australia"] = {gk:[{n:"M. Ryan",c:"AZ",a:33,ca:85},{n:"J. Gauci",c:"Aston Villa",a:24,ca:5},{n:"L. Redmayne",c:"Sydney",a:36,ca:10}],df:[{n:"H. Souttar",c:"Sheffield Utd",a:26,ca:35},{n:"K. Rowles",c:"Hearts",a:27,ca:20},{n:"B. Smith",c:"Man City",a:25,ca:5},{n:"C. Elder",c:"Wrexham",a:30,ca:20},{n:"A. Behich",c:"Melbourne City",a:34,ca:60},{n:"R. Strain",c:"Dundee Utd",a:27,ca:10},{n:"C. Burgess",c:"Birmingham",a:29,ca:10},{n:"T. Deng",c:"Albirex Niigata",a:28,ca:5}],mf:[{n:"J. Irvine",c:"St. Pauli",a:32,ca:60},{n:"C. Goodwin",c:"Adelaide",a:33,ca:25},{n:"K. Baccus",c:"Melbourne City",a:27,ca:20},{n:"R. McGree",c:"Middlesbrough",a:26,ca:25},{n:"A. Devlin",c:"Heart of Midlothian",a:31,ca:15},{n:"D. Arzani",c:"Melbourne Victory",a:26,ca:10},{n:"P. Yazbek",c:"Viking",a:23,ca:3},{n:"A. Robertson",c:"Melbourne City",a:24,ca:2}],fw:[{n:"M. Duke",c:"Machida Zelvia",a:34,ca:40},{n:"A. Kuol",c:"Hearts",a:23,ca:8},{n:"N. D'Agostino",c:"Melbourne Victory",a:26,ca:15},{n:"B. Borello",c:"Western Sydney",a:25,ca:5},{n:"J. Silvera",c:"Middlesbrough",a:23,ca:5},{n:"M. Boyle",c:"Hibernian",a:32,ca:25}]};
teamsData["Paraguay"] = {gk:[{n:"C. Coronel",c:"Botafogo",a:31,ca:15},{n:"A. Silva",c:"Independiente",a:28,ca:5},{n:"J. Espínola",c:"Olimpia",a:26,ca:3}],df:[{n:"G. Gómez",c:"Palmeiras",a:32,ca:75},{n:"F. Balbuena",c:"Dinamo Moscú",a:33,ca:40},{n:"J. Alonso",c:"Lanus",a:31,ca:25},{n:"B. Rivarola",c:"Saprissa",a:28,ca:10},{n:"A. Espínola",c:"Olimpia",a:26,ca:5},{n:"R. Rojas",c:"Olimpia",a:28,ca:15},{n:"S. Gamarra",c:"Libertad",a:24,ca:5},{n:"I. Mareco",c:"Cuiabá",a:25,ca:3}],mf:[{n:"M. Villasanti",c:"Palmeiras",a:28,ca:30},{n:"D. Gómez",c:"Olimpia",a:27,ca:10},{n:"R. Bobadilla",c:"São Paulo",a:25,ca:10},{n:"Á. Romero",c:"Corinthians",a:27,ca:15},{n:"H. Ojeda",c:"Cerro Porteño",a:27,ca:8},{n:"F. Domínguez",c:"Cerro Porteño",a:26,ca:5},{n:"M. Rojas",c:"Olimpia",a:23,ca:3},{n:"A. Arce",c:"Cerro Porteño",a:24,ca:2}],fw:[{n:"A. Sanabria",c:"Torino",a:29,ca:35},{n:"M. Ávalos",c:"Chicago Fire",a:27,ca:15},{n:"R. Bareiro",c:"San Lorenzo",a:28,ca:10},{n:"C. Ferreira",c:"Olimpia",a:22,ca:5},{n:"J. Enciso",c:"Brighton",a:21,ca:10},{n:"K. Parzajuk",c:"Olimpia",a:24,ca:3}]};
teamsData["Turquía"] = {gk:[{n:"M. Günok",c:"Beşiktaş",a:36,ca:40},{n:"U. Çakır",c:"Trabzonspor",a:29,ca:30},{n:"D. Alemdar",c:"Rennes",a:22,ca:5}],df:[{n:"K. Ayhan",c:"Galatasaray",a:33,ca:60},{n:"M. Çelik",c:"Roma",a:28,ca:50},{n:"A. Bardakcı",c:"Galatasaray",a:29,ca:15},{n:"F. Kadioglu",c:"Brighton",a:25,ca:20},{n:"C. Söyüncü",c:"Fenerbahçe",a:29,ca:60},{n:"E. Elmali",c:"Trabzonspor",a:25,ca:10},{n:"R. Yılmaz",c:"Rayo Vallecano",a:23,ca:8},{n:"O. Kabak",c:"Hoffenheim",a:25,ca:25}],mf:[{n:"H. Çalhanoğlu",c:"Inter",a:31,ca:95},{n:"S. Akbaba",c:"Galatasaray",a:29,ca:10},{n:"O. Kökçü",c:"Benfica",a:24,ca:35},{n:"S. Özcan",c:"Bournemouth",a:27,ca:20},{n:"İ. Yüksek",c:"Fenerbahçe",a:25,ca:15},{n:"A. Kahveci",c:"Fenerbahçe",a:31,ca:30},{n:"Y. Yazıcı",c:"Lille",a:28,ca:45}],fw:[{n:"K. Yıldız",c:"Juventus",a:20,ca:15},{n:"C. Ünder",c:"Fenerbahçe",a:28,ca:50},{n:"B. Yılmaz",c:"Galatasaray",a:24,ca:10},{n:"E. Dursun",c:"Alanyaspor",a:30,ca:10},{n:"İ. Kahveci",c:"Fenerbahçe",a:30,ca:35},{n:"U. Nayir",c:"Beşiktaş",a:28,ca:5}]};
teamsData["Estados Unidos"] = {gk:[{n:"M. Turner",c:"Crystal Palace",a:31,ca:45},{n:"E. Horvath",c:"Cardiff",a:30,ca:10},{n:"P. Schulte",c:"Columbus",a:24,ca:3}],df:[{n:"S. Robinson",c:"Fulham",a:28,ca:50},{n:"C. Richards",c:"Crystal Palace",a:25,ca:20},{n:"M. McKenzie",c:"Toulouse",a:26,ca:15},{n:"A. Robinson",c:"Fulham",a:28,ca:55},{n:"J. Scally",c:"Gladbach",a:23,ca:15},{n:"K. Paredes",c:"Wolfsburg",a:22,ca:5},{n:"C. Carter-Vickers",c:"Celtic",a:27,ca:15},{n:"D. Yedlin",c:"Inter Miami",a:32,ca:80}],mf:[{n:"T. Adams",c:"Bournemouth",a:26,ca:45},{n:"Y. Musah",c:"Milan",a:22,ca:40},{n:"W. McKennie",c:"Juventus",a:26,ca:60},{n:"G. Reyna",c:"Dortmund",a:22,ca:35},{n:"L. de la Torre",c:"San Diego",a:27,ca:15},{n:"A. Tillman",c:"PSV",a:24,ca:15},{n:"J. Aaronson",c:"Leeds",a:24,ca:40},{n:"B. Aaronson",c:"Leeds",a:24,ca:35}],fw:[{n:"C. Pulisic",c:"Milan",a:26,ca:75},{n:"F. Balogun",c:"Monaco",a:24,ca:15},{n:"T. Weah",c:"Juventus",a:25,ca:40},{n:"B. Sargent",c:"Norwich",a:25,ca:25},{n:"H. Wright",c:"Coventry",a:27,ca:15},{n:"J. Sargent",c:"Norwich City",a:25,ca:25}]};

// E
teamsData["Curazao"] = {gk:[{n:"T. Room",c:"Bochum",a:36,ca:40},{n:"E. Antonise",c:"Scherpenheuvel",a:30,ca:5},{n:"R. Lupson",c:"Sittard",a:30,ca:5}],df:[{n:"M. Leoni",c:"Sittard",a:28,ca:15},{n:"J. Gaari",c:"RVKSV",a:32,ca:25},{n:"K. Cijntje",c:"Scherpenheuvel",a:26,ca:5},{n:"N. Alberto",c:"CSD",a:25,ca:3},{n:"C. Martina",c:"NAC Breda",a:35,ca:60},{n:"R. Troupee",c:"Sittard",a:24,ca:5},{n:"S. Bodak",c:"Scherpenheuvel",a:25,ca:2}],mf:[{n:"V. Anita",c:"Sheffield Utd",a:36,ca:30},{n:"B. Sekou",c:"Scherpenheuvel",a:28,ca:10},{n:"J. Bacuna",c:"Aston Villa",a:31,ca:20},{n:"L. Bacuna",c:"Birmingham",a:31,ca:15},{n:"K. Felida",c:"RVKSV",a:25,ca:3},{n:"R. Barradas",c:"Scherpenheuvel",a:27,ca:5},{n:"S. van den Hurk",c:"MVV",a:30,ca:10}],fw:[{n:"A. Janga",c:"Roda",a:35,ca:20},{n:"R. Meulens",c:"Scherpenheuvel",a:30,ca:10},{n:"L. Carolina",c:"Sittard",a:25,ca:5},{n:"J. Zimmerman",c:"RVKSV",a:30,ca:8},{n:"D. van Duinen",c:"Almere",a:30,ca:15},{n:"R. Rigid",c:"Scherpenheuvel",a:25,ca:3}]};
teamsData["Ecuador"] = {gk:[{n:"H. Galíndez",c:"Huracán",a:38,ca:20},{n:"M. Ramírez",c:"Ind. del Valle",a:24,ca:5},{n:"A. Domínguez",c:"LDU Quito",a:37,ca:60}],df:[{n:"P. Hincapié",c:"Bayer Leverkusen",a:23,ca:40},{n:"F. Torres",c:"Corinthians",a:28,ca:35},{n:"W. Pacho",c:"PSG",a:23,ca:20},{n:"Á. Preciado",c:"Sparta Praga",a:27,ca:30},{n:"J. Caicedo",c:"Barcelona SC",a:27,ca:10},{n:"L. Realpe",c:"Red Bull Bragantino",a:24,ca:5},{n:"A. Porozo",c:"Santos",a:25,ca:10},{n:"B. Castillo",c:"Barcelona SC",a:26,ca:5}],mf:[{n:"M. Caicedo",c:"Chelsea",a:23,ca:50},{n:"C. Gruezo",c:"RB Bragantino",a:30,ca:55},{n:"A. Franco",c:"Talleres",a:26,ca:10},{n:"J. Sarmiento",c:"Ipswich",a:23,ca:15},{n:"K. Rodríguez",c:"Ind. del Valle",a:24,ca:5},{n:"P. Vite",c:"Vancouver",a:23,ca:8},{n:"E. Valencia",c:"Barcelona SC",a:26,ca:10},{n:"J. Quiñónez",c:"Barcelona SC",a:24,ca:3}],fw:[{n:"E. Valencia",c:"Flamengo",a:35,ca:90},{n:"K. Arroyo",c:"Santos",a:22,ca:5},{n:"G. Plata",c:"Al Sadd",a:25,ca:40},{n:"J. Cifuentes",c:"Rangers",a:26,ca:10},{n:"M. Corozo",c:"Barcelona SC",a:26,ca:5},{n:"A. Mena",c:"Emelec",a:24,ca:3}]};
teamsData["Alemania"] = {gk:[{n:"M. Neuer",c:"Bayern",a:39,ca:120},{n:"M. ter Stegen",c:"Barcelona",a:33,ca:40},{n:"O. Baumann",c:"Hoffenheim",a:31,ca:5}],df:[{n:"A. Rüdiger",c:"Real Madrid",a:32,ca:80},{n:"J. Kimmich",c:"Bayern",a:30,ca:95},{n:"N. Schlotterbeck",c:"Dortmund",a:25,ca:15},{n:"D. Raum",c:"RB Leipzig",a:27,ca:20},{n:"T. Tah",c:"Bayer Leverkusen",a:29,ca:35},{n:"M. Ginter",c:"Freiburg",a:31,ca:55},{n:"R. Gosens",c:"Union Berlin",a:31,ca:25},{n:"J. Tah",c:"Bayer Leverkusen",a:29,ca:35}],mf:[{n:"İ. Gündoğan",c:"Man City",a:34,ca:75},{n:"J. Musiala",c:"Bayern",a:22,ca:40},{n:"F. Wirtz",c:"Bayer Leverkusen",a:22,ca:30},{n:"L. Sané",c:"Bayern",a:29,ca:65},{n:"P. Groß",c:"Dortmund",a:33,ca:15},{n:"R. Andrich",c:"Bayer Leverkusen",a:30,ca:15},{n:"A. Pavlović",c:"Bayern",a:21,ca:5},{n:"E. Can",c:"Dortmund",a:31,ca:45}],fw:[{n:"N. Füllkrug",c:"West Ham",a:32,ca:15},{n:"K. Havertz",c:"Arsenal",a:26,ca:55},{n:"T. Müller",c:"Bayern",a:35,ca:130},{n:"J. Burkardt",c:"Mainz",a:24,ca:5},{n:"K. Adeyemi",c:"Dortmund",a:23,ca:10},{n:"J. Wirtz",c:"Bayer",a:22,ca:30}]};
teamsData["Costa de Marfil"] = {gk:[{n:"Y. Fofana",c:"Angers",a:33,ca:30},{n:"C. Cissé",c:"Amiens",a:27,ca:10},{n:"M. Diaby",c:"Wydad",a:25,ca:5}],df:[{n:"S. Aurier",c:"Galatasaray",a:32,ca:95},{n:"W. Boly",c:"Nottingham",a:34,ca:40},{n:"E. Diakité",c:"Reims",a:24,ca:10},{n:"H. Traorè",c:"Real Betis",a:32,ca:30},{n:"E. Tapsoba",c:"Bayer Leverkusen",a:26,ca:35},{n:"N. Boga",c:"Nice",a:28,ca:15},{n:"O. Diomandé",c:"Sporting",a:21,ca:8},{n:"C. Kipré",c:"West Brom",a:28,ca:10}],mf:[{n:"S. Fofana",c:"AC Milan",a:30,ca:40},{n:"F. Kessié",c:"Al Ahli",a:28,ca:75},{n:"J. Seri",c:"Hull City",a:34,ca:40},{n:"H. Kamara",c:"Lyon",a:24,ca:10},{n:"I. Sangaré",c:"Nottingham",a:27,ca:25},{n:"M. Bamba",c:"Celtic",a:28,ca:15},{n:"J. Boga",c:"Nice",a:28,ca:15},{n:"K. Dabila",c:"Mouloudia",a:24,ca:5}],fw:[{n:"S. Haller",c:"Bremen",a:31,ca:40},{n:"J. Krasso",c:"Red Star",a:27,ca:10},{n:"M. Gradel",c:"St Etienne",a:37,ca:30},{n:"K. Kone",c:"Udinese",a:27,ca:10},{n:"D. Oulai",c:"San Pedro",a:25,ca:3},{n:"G. Diomandé",c:"San Pedro",a:24,ca:2}]};

// F
teamsData["Japón"] = {gk:[{n:"Z. Suzuki",c:"Parma",a:23,ca:5},{n:"K. Osako",c:"Sanfrecce",a:25,ca:5},{n:"K. Kawashima",c:"Strasbourg",a:42,ca:95}],df:[{n:"K. Itakura",c:"Gladbach",a:28,ca:30},{n:"H. Ito",c:"Bayern",a:26,ca:25},{n:"Y. Osako",c:"Köln",a:32,ca:20},{n:"S. Sasaki",c:"Sanfrecce",a:25,ca:10},{n:"Y. Nagatomo",c:"FC Tokio",a:38,ca:140},{n:"T. Tomiyasu",c:"Arsenal",a:26,ca:45},{n:"K. Machida",c:"Kashima",a:28,ca:10},{n:"R. Sugiura",c:"Yokohama",a:26,ca:5}],mf:[{n:"W. Endo",c:"Liverpool",a:32,ca:60},{n:"H. Morita",c:"Sporting",a:30,ca:30},{n:"D. Kamada",c:"Crystal Palace",a:28,ca:40},{n:"T. Kubo",c:"Real Sociedad",a:24,ca:40},{n:"K. Tanaka",c:"Düsseldorf",a:31,ca:35},{n:"R. Doan",c:"Freiburg",a:27,ca:40},{n:"K. Mitoma",c:"Brighton",a:28,ca:20},{n:"A. Ito",c:"Gladbach",a:25,ca:15}],fw:[{n:"A. Ueda",c:"Feyenoord",a:26,ca:20},{n:"D. Maeda",c:"Celtic",a:27,ca:15},{n:"K. Ogawa",c:"NEC",a:27,ca:10},{n:"K. Furuhashi",c:"Celtic",a:30,ca:15},{n:"Y. Ohashi",c:"Sanfrecce",a:24,ca:5},{n:"T. Asano",c:"Mallorca",a:30,ca:50}]};
teamsData["Países Bajos"] = {gk:[{n:"J. Bijlow",c:"Feyenoord",a:27,ca:10},{n:"M. Flekken",c:"Brentford",a:32,ca:15},{n:"B. Verbruggen",c:"Brighton",a:23,ca:5}],df:[{n:"V. van Dijk",c:"Liverpool",a:34,ca:75},{n:"N. Aké",c:"Man City",a:30,ca:55},{n:"D. Dumfries",c:"Inter",a:29,ca:60},{n:"M. de Ligt",c:"Man Utd",a:25,ca:50},{n:"J. Timber",c:"Arsenal",a:24,ca:20},{n:"N. Frimpong",c:"Bayer Leverkusen",a:24,ca:10},{n:"Q. Hartman",c:"Feyenoord",a:23,ca:5},{n:"S. van de Ven",c:"Tottenham",a:24,ca:10}],mf:[{n:"F. de Jong",c:"Barcelona",a:28,ca:60},{n:"T. Koopmeiners",c:"Juventus",a:27,ca:30},{n:"J. Veerman",c:"PSV",a:26,ca:15},{n:"M. Wieffer",c:"Brighton",a:25,ca:15},{n:"R. Gravenberch",c:"Liverpool",a:23,ca:15},{n:"K. Taylor",c:"Ajax",a:22,ca:8},{n:"G. Wijnaldum",c:"Al Ettifaq",a:33,ca:95},{n:"X. Simons",c:"RB Leipzig",a:22,ca:20}],fw:[{n:"M. Depay",c:"Corinthians",a:31,ca:95},{n:"C. Gakpo",c:"Liverpool",a:26,ca:35},{n:"D. Malen",c:"Dortmund",a:26,ca:30},{n:"B. Brobbey",c:"Ajax",a:23,ca:10},{n:"J. Fink",c:"PSV",a:22,ca:5},{n:"W. Weghorst",c:"Ajax",a:32,ca:40}]};
teamsData["Suecia"] = {gk:[{n:"R. Olsen",c:"Monaco",a:35,ca:50},{n:"K. Nordfeldt",c:"AIK",a:36,ca:15},{n:"L. Dahlin",c:"FC Copenhague",a:30,ca:5}],df:[{n:"V. Lindelöf",c:"Man Utd",a:31,ca:70},{n:"A. Ekdal",c:"Burnley",a:26,ca:20},{n:"L. Augustinsson",c:"Anderlecht",a:31,ca:45},{n:"E. Hien",c:"Atalanta",a:25,ca:15},{n:"E. Krafth",c:"Newcastle",a:30,ca:40},{n:"J. Gudmundsson",c:"AIK",a:24,ca:5},{n:"G. Lagerbielke",c:"Twente",a:24,ca:3},{n:"S. Larsson",c:"AIK",a:33,ca:40}],mf:[{n:"K. Olsson",c:"Midtjylland",a:30,ca:30},{n:"J. Karlström",c:"PAOK",a:29,ca:15},{n:"H. Ekdal",c:"Brommapojkarna",a:26,ca:5},{n:"M. Rohdén",c:"Frosinone",a:33,ca:20},{n:"E. Andersson",c:"CAHN",a:27,ca:8},{n:"W. Swedberg",c:"Celta",a:21,ca:5},{n:"S. Larsson",c:"AIK",a:33,ca:40},{n:"J. Cajuste",c:"Ipswich",a:25,ca:10}],fw:[{n:"V. Gyökeres",c:"Sporting",a:27,ca:20},{n:"A. Elanga",c:"Nottingham",a:23,ca:15},{n:"J. Okonkwo",c:"Malmö",a:26,ca:5},{n:"J. Nilsson",c:"Stuttgart",a:30,ca:10},{n:"E. Holm",c:"Malmö",a:24,ca:5},{n:"O. Berg",c:"Malmö",a:29,ca:10}]};
teamsData["Túnez"] = {gk:[{n:"B. Said",c:"US Monastir",a:32,ca:10},{n:"A. Memmiche",c:"Espérance",a:26,ca:5},{n:"E. Ben Mustapha",c:"Al Fayha",a:35,ca:50}],df:[{n:"M. Bronn",c:"Servette",a:29,ca:40},{n:"D. Draeger",c:"Holstein Kiel",a:26,ca:5},{n:"Y. Meriah",c:"Espérance",a:31,ca:60},{n:"M. Talbi",c:"Lorient",a:27,ca:30},{n:"A. Maâloul",c:"Al Ahly",a:34,ca:85},{n:"H. Mathlouthi",c:"Zamalek",a:28,ca:15},{n:"B. Ifa",c:"Kuweit SC",a:30,ca:10},{n:"H. Laâbidi",c:"Club Africain",a:25,ca:5}],mf:[{n:"C. Sassi",c:"Al Qadsiah",a:27,ca:10},{n:"E. Skhiri",c:"Eintracht",a:30,ca:55},{n:"H. Mejbri",c:"Burnley",a:22,ca:10},{n:"A. Laïdouni",c:"Al Duhail",a:28,ca:35},{n:"M. Ben Romdhane",c:"Espérance",a:25,ca:15},{n:"N. Sliti",c:"Al Ahli",a:32,ca:70},{n:"Y. Msakni",c:"Al Arabi",a:34,ca:95},{n:"F. Sassi",c:"Al Qadsiah",a:27,ca:10}],fw:[{n:"S. Jaziri",c:"Zamalek",a:32,ca:30},{n:"Y. Khenissi",c:"Kuweit SC",a:33,ca:50},{n:"E. Achouri",c:"Copenhague",a:26,ca:15},{n:"A. Haddadi",c:"Espérance",a:26,ca:5},{n:"F. Ben Larbi",c:"Club Africain",a:25,ca:3},{n:"H. Ben Tahar",c:"Espérance",a:24,ca:2}]};

// G
teamsData["Bélgica"] = {gk:[{n:"K. Schmeichel",c:"Anderlecht",a:38,ca:85},{n:"M. Sels",c:"Nottingham",a:33,ca:15},{n:"T. Casteels",c:"Al Qadsiah",a:33,ca:20}],df:[{n:"T. Alderweireld",c:"Antwerp",a:36,ca:130},{n:"J. Vertonghen",c:"Anderlecht",a:38,ca:160},{n:"W. Faes",c:"Leicester",a:27,ca:25},{n:"Z. Debast",c:"Sporting",a:21,ca:10},{n:"T. Castagne",c:"Fulham",a:29,ca:50},{n:"A. Theate",c:"Frankfurt",a:25,ca:20},{n:"R. Meunier",c:"Lille",a:33,ca:60},{n:"A. Witsel",c:"Atlético",a:36,ca:130}],mf:[{n:"K. De Bruyne",c:"Man City",a:34,ca:105},{n:"Y. Tielemans",c:"Aston Villa",a:29,ca:75},{n:"A. Onana",c:"Aston Villa",a:23,ca:15},{n:"O. Mangala",c:"Lyon",a:27,ca:20},{n:"H. Vanaken",c:"Club Brugge",a:32,ca:30},{n:"M. Lavia",c:"Chelsea",a:21,ca:10},{n:"D. Praet",c:"Anderlecht",a:31,ca:35},{n:"L. Trossard",c:"Arsenal",a:30,ca:35}],fw:[{n:"R. Lukaku",c:"Napoli",a:32,ca:120},{n:"L. Openda",c:"RB Leipzig",a:25,ca:25},{n:"J. Doku",c:"Man City",a:23,ca:25},{n:"C. De Ketelaere",c:"Atalanta",a:24,ca:20},{n:"D. Lukebakio",c:"Sevilla",a:27,ca:15},{n:"M. Batshuayi",c:"Galatasaray",a:31,ca:50}]};
teamsData["Egipto"] = {gk:[{n:"M. El Shenawy",c:"Al Ahly",a:36,ca:50},{n:"M. Awad",c:"Zamalek",a:31,ca:10},{n:"M. Sobhy",c:"Al Ahly",a:25,ca:5}],df:[{n:"M. Hany",c:"Al Ahly",a:29,ca:25},{n:"R. Saïd",c:"Pyramids",a:29,ca:10},{n:"A. Hegazy",c:"Al Ittihad",a:34,ca:85},{n:"M. Abdelmonem",c:"Nice",a:26,ca:15},{n:"M. Hamdy",c:"Pyramids",a:29,ca:10},{n:"A. Fotouh",c:"Zamalek",a:26,ca:10},{n:"O. Kamal",c:"Future",a:28,ca:8},{n:"H. Samy",c:"Al Ahly",a:27,ca:5}],mf:[{n:"M. Elneny",c:"Al Jazira",a:33,ca:100},{n:"H. Fathy",c:"Al Ahly",a:31,ca:20},{n:"A. El Sisi",c:"Pyramids",a:30,ca:15},{n:"I. Adel",c:"Pyramids",a:27,ca:10},{n:"M. Afsha",c:"Al Ahly",a:29,ca:25},{n:"O. Marmoush",c:"Man City",a:26,ca:30},{n:"Z. Kamal",c:"Zamalek",a:26,ca:3},{n:"M. Trezeguet",c:"Trabzonspor",a:30,ca:55}],fw:[{n:"M. Salah",c:"Liverpool",a:33,ca:100},{n:"A. Kouka",c:"Alanyaspor",a:32,ca:35},{n:"O. Faisal",c:"Future",a:25,ca:3},{n:"S. Ibrahim",c:"Ceramica",a:25,ca:2},{n:"M. Hamdy",c:"Pyramids",a:29,ca:10},{n:"K. Lasheen",c:"Pyramids",a:28,ca:10}]};
teamsData["Irán"] = {gk:[{n:"A. Beiranvand",c:"Persepolis",a:32,ca:70},{n:"P. Niazmand",c:"Sepahan",a:30,ca:10},{n:"H. Hosseini",c:"Esteghlal",a:32,ca:30}],df:[{n:"S. Moharrami",c:"Dinamo Zagreb",a:29,ca:30},{n:"M. Kanani",c:"Persepolis",a:34,ca:50},{n:"H. Hosseini",c:"Tractor",a:33,ca:30},{n:"R. Rezaeian",c:"Sepahan",a:33,ca:50},{n:"M. Abdul",c:"Tractor",a:25,ca:5},{n:"M. Ghaseminejad",c:"Persepolis",a:30,ca:10},{n:"O. Noorafkan",c:"Sepahan",a:28,ca:15},{n:"A. Nemati",c:"Persepolis",a:30,ca:10}],mf:[{n:"S. Ezatolahi",c:"Al Ahli",a:29,ca:60},{n:"A. Gholizadeh",c:"Lech Poznań",a:31,ca:35},{n:"M. Mohebi",c:"Esteghlal",a:27,ca:15},{n:"S. Ghoddos",c:"Kalmar",a:32,ca:50},{n:"M. Karimi",c:"Persepolis",a:27,ca:20},{n:"A. Jahanbakhsh",c:"Feyenoord",a:31,ca:85},{n:"M. Torabi",c:"Persepolis",a:30,ca:35},{n:"N. Torabi",c:"Persepolis",a:30,ca:30}],fw:[{n:"S. Azmoun",c:"Roma",a:30,ca:80},{n:"M. Taremi",c:"Inter",a:32,ca:85},{n:"R. Javad",c:"Persepolis",a:25,ca:5},{n:"A. Sadeghi",c:"Esteghlal",a:24,ca:3},{n:"K. Ansarifard",c:"AEK",a:35,ca:100},{n:"Y. Salmani",c:"Persepolis",a:24,ca:5}]};
teamsData["Nueva Zelanda"] = {gk:[{n:"M. Marinovic",c:"Wellington",a:37,ca:30},{n:"N. Sail",c:"Auckland FC",a:26,ca:5},{n:"J. Knowles",c:"Wellington",a:26,ca:3}],df:[{n:"W. Reid",c:"Auckland FC",a:36,ca:25},{n:"T. Smith",c:"Auckland FC",a:35,ca:50},{n:"N. Pijnaker",c:"Auckland FC",a:27,ca:15},{n:"M. Stamenic",c:"Auckland FC",a:27,ca:10},{n:"D. Supyk",c:"Auckland FC",a:24,ca:2},{n:"L. Toomey",c:"Auckland FC",a:25,ca:3},{n:"S. Kelly",c:"Auckland FC",a:30,ca:5},{n:"T. Payton",c:"Auckland FC",a:25,ca:3}],mf:[{n:"J. Bell",c:"Auckland FC",a:30,ca:10},{n:"C. Howieson",c:"Auckland FC",a:30,ca:15},{n:"M. Ridenton",c:"Auckland FC",a:28,ca:10},{n:"S. Singh",c:"Auckland FC",a:29,ca:10},{n:"A. Rufer",c:"Wellington",a:28,ca:10},{n:"E. Grieve",c:"Auckland FC",a:27,ca:5},{n:"B. Waine",c:"Plymouth",a:30,ca:10},{n:"J. Champness",c:"Auckland FC",a:28,ca:5}],fw:[{n:"C. Wood",c:"Nottingham",a:33,ca:75},{n:"M. Woud",c:"Wellington",a:26,ca:5},{n:"E. Garbett",c:"Auckland FC",a:24,ca:3},{n:"K. Barbarouses",c:"Wellington",a:35,ca:60},{n:"R. de Vries",c:"Auckland FC",a:25,ca:3},{n:"B. Old",c:"Auckland FC",a:24,ca:2}]};

// H
teamsData["Cabo Verde"] = {gk:[{n:"J. Correia",c:"Académica",a:29,ca:10},{n:"K. Silva",c:"União",a:28,ca:5},{n:"D. Rocha",c:"Mindelense",a:26,ca:3}],df:[{n:"S. Lopes",c:"Mafra",a:28,ca:15},{n:"R. Santos",c:"Tondela",a:31,ca:10},{n:"D. Tavares",c:"Arouca",a:26,ca:5},{n:"F. Varela",c:"Valencia",a:30,ca:15},{n:"C. Semedo",c:"Vilafranquense",a:27,ca:5},{n:"L. Lopes",c:"Mafra",a:25,ca:3},{n:"K. Rocha",c:"Sporting",a:24,ca:2}],mf:[{n:"R. Mendes",c:"Flamengo",a:30,ca:15},{n:"P. Lopes",c:"Mafra",a:27,ca:10},{n:"J. Tavares",c:"Arouca",a:28,ca:8},{n:"K. Andrade",c:"Flamengo",a:30,ca:10},{n:"N. Lopes",c:"Mafra",a:25,ca:3},{n:"C. Mendes",c:"Académica",a:26,ca:5},{n:"R. Lopes",c:"Académica",a:24,ca:2}],fw:[{n:"J. Tavares",c:"Arouca",a:28,ca:8},{n:"K. Santos",c:"Mafra",a:28,ca:5},{n:"R. Gomes",c:"Mafra",a:27,ca:5},{n:"D. Duarte",c:"Mindelense",a:25,ca:3},{n:"S. Fortes",c:"Académica",a:26,ca:4},{n:"A. Santos",c:"Mindelense",a:25,ca:2}]};
teamsData["Arabia Saudita"] = {gk:[{n:"M. Al-Owais",c:"Al Hilal",a:33,ca:50},{n:"N. Al-Aqidi",c:"Al Nassr",a:29,ca:10},{n:"R. Al-Sanousi",c:"Al Ahli",a:25,ca:5}],df:[{n:"S. Abdulhamid",c:"Roma",a:26,ca:35},{n:"H. Tambakti",c:"Al Hilal",a:26,ca:20},{n:"A. Al-Bulayhi",c:"Al Hilal",a:35,ca:50},{n:"A. Lajami",c:"Al Hilal",a:29,ca:10},{n:"Z. Al-Ghamdi",c:"Al Ahli",a:28,ca:10},{n:"M. Al-Shahrani",c:"Al Hilal",a:33,ca:80},{n:"N. Al-Dawsari",c:"Al Hilal",a:26,ca:5},{n:"S. Al-Harbi",c:"Al Ittihad",a:24,ca:3}],mf:[{n:"K. Al-Dawsari",c:"Al Hilal",a:30,ca:10},{n:"A. Kanno",c:"Al Hilal",a:30,ca:45},{n:"M. Al-Khaibari",c:"Al Ahli",a:32,ca:15},{n:"A. Al-Ghamdi",c:"Al Ittihad",a:24,ca:5},{n:"F. Al-Malki",c:"Al Ittihad",a:30,ca:10},{n:"H. Al-Faraj",c:"Al Hilal",a:32,ca:75},{n:"A. Otayf",c:"Al Nassr",a:32,ca:40},{n:"S. Al-Nabit",c:"Al Hilal",a:26,ca:5}],fw:[{n:"S. Al-Dawsari",c:"Al Hilal",a:33,ca:85},{n:"F. Al-Buraikan",c:"Al Ahli",a:25,ca:30},{n:"A. Yariri",c:"Al Khaleej",a:25,ca:10},{n:"H. Asiri",c:"Al Ittihad",a:24,ca:5},{n:"S. Al-Ghamdi",c:"Al Ittihad",a:25,ca:3},{n:"A. Al-Hassan",c:"Al Nassr",a:26,ca:5}]};
teamsData["España"] = {gk:[{n:"U. Simón",c:"Athletic",a:28,ca:50},{n:"A. Remiro",c:"Real Sociedad",a:30,ca:15},{n:"David Raya",c:"Arsenal",a:29,ca:10}],df:[{n:"D. Carvajal",c:"Real Madrid",a:33,ca:50},{n:"R. Le Normand",c:"Real Madrid",a:28,ca:20},{n:"P. Torres",c:"Aston Villa",a:28,ca:30},{n:"A. Laporte",c:"Al Nassr",a:31,ca:40},{n:"J. Navas",c:"Sevilla",a:39,ca:55},{n:"A. Balde",c:"Barcelona",a:21,ca:10},{n:"D. Vivian",c:"Athletic",a:25,ca:5},{n:"M. Casado",c:"Barcelona",a:25,ca:5}],mf:[{n:"Rodri",c:"Man City",a:29,ca:60},{n:"Pedri",c:"Barcelona",a:22,ca:30},{n:"F. Ruiz",c:"PSG",a:29,ca:30},{n:"M. Merino",c:"Arsenal",a:29,ca:25},{n:"Gavi",c:"Barcelona",a:20,ca:30},{n:"D. Olmo",c:"Barcelona",a:27,ca:40},{n:"M. Zubimendi",c:"Real Sociedad",a:26,ca:15},{n:"A. Baena",c:"Villarreal",a:23,ca:8}],fw:[{n:"L. Yamal",c:"Barcelona",a:18,ca:20},{n:"N. Williams",c:"Athletic",a:22,ca:20},{n:"Á. Morata",c:"AC Milan",a:32,ca:80},{n:"M. Oyarzabal",c:"Real Sociedad",a:28,ca:35},{n:"Joselu",c:"Real Madrid",a:35,ca:15},{n:"F. Torres",c:"Barcelona",a:25,ca:40}]};
teamsData["Uruguay"] = {gk:[{n:"S. Rochet",c:"Internacional",a:32,ca:30},{n:"F. Mele",c:"Peñarol",a:31,ca:5},{n:"R. Rodríguez",c:"Nacional",a:28,ca:5}],df:[{n:"R. Araujo",c:"Barcelona",a:26,ca:25},{n:"J. Giménez",c:"Atlético Madrid",a:30,ca:85},{n:"M. Olivera",c:"Napoli",a:27,ca:15},{n:"N. Nández",c:"Qadsiah",a:30,ca:55},{n:"M. Cáceres",c:"Nacional",a:38,ca:120},{n:"S. Bueno",c:"Girona",a:26,ca:10},{n:"L. Suárez",c:"Gremio",a:38,ca:145},{n:"G. Píriz",c:"Peñarol",a:25,ca:5}],mf:[{n:"F. Valverde",c:"Real Madrid",a:27,ca:65},{n:"M. Vecino",c:"Lazio",a:33,ca:70},{n:"R. Bentancur",c:"Tottenham",a:28,ca:65},{n:"G. de Arrascaeta",c:"Flamengo",a:31,ca:50},{n:"N. Fonseca",c:"Nacional",a:26,ca:10},{n:"E. Carballo",c:"Flamengo",a:29,ca:10},{n:"F. Pellistri",c:"Man Utd",a:23,ca:20},{n:"B. Arezo",c:"Nacional",a:25,ca:5}],fw:[{n:"D. Núñez",c:"Liverpool",a:26,ca:35},{n:"F. Torres",c:"Orlando",a:24,ca:5},{n:"M. Araújo",c:"Racing",a:26,ca:10},{n:"C. Olivera",c:"LAFC",a:25,ca:5},{n:"L. Rodríguez",c:"Peñarol",a:26,ca:5},{n:"A. Canobbio",c:"Fluminense",a:26,ca:10}]};

// I
teamsData["Francia"] = {gk:[{n:"M. Maignan",c:"AC Milan",a:30,ca:25},{n:"A. Areola",c:"West Ham",a:32,ca:5},{n:"L. Chevalier",c:"Lille",a:23,ca:3}],df:[{n:"T. Hernández",c:"AC Milan",a:27,ca:35},{n:"W. Saliba",c:"Arsenal",a:24,ca:25},{n:"D. Upamecano",c:"Bayern",a:26,ca:25},{n:"J. Koundé",c:"Barcelona",a:26,ca:35},{n:"L. Hernández",c:"PSG",a:29,ca:40},{n:"J. Clauss",c:"OGC Nice",a:32,ca:15},{n:"B. Pavard",c:"Inter",a:29,ca:50},{n:"I. Konaté",c:"Liverpool",a:26,ca:15}],mf:[{n:"A. Tchouaméni",c:"Real Madrid",a:25,ca:40},{n:"E. Camavinga",c:"Real Madrid",a:22,ca:20},{n:"W. Zaïre-Emery",c:"PSG",a:19,ca:5},{n:"Y. Fofana",c:"AC Milan",a:26,ca:10},{n:"A. Rabiot",c:"Marseille",a:30,ca:50},{n:"M. Olise",c:"Bayern",a:23,ca:15},{n:"R. Kolo Muani",c:"PSG",a:26,ca:20},{n:"K. Diouf",c:"Lens",a:24,ca:5}],fw:[{n:"K. Mbappé",c:"Real Madrid",a:26,ca:85},{n:"A. Griezmann",c:"Atlético",a:34,ca:135},{n:"O. Dembélé",c:"PSG",a:28,ca:50},{n:"M. Thuram",c:"Inter",a:27,ca:30},{n:"K. Coman",c:"Bayern",a:29,ca:55},{n:"B. Barcola",c:"PSG",a:22,ca:10}]};
teamsData["Irak"] = {gk:[{n:"J. Hassan",c:"Al Zawraa",a:33,ca:75},{n:"A. Hasan",c:"Al Shorta",a:30,ca:10},{n:"M. Hameed",c:"Al Quwa",a:31,ca:20}],df:[{n:"M. Rekany",c:"Al Quwa",a:27,ca:15},{n:"S. Nadhim",c:"Al Shorta",a:31,ca:30},{n:"A. Yahya",c:"Al Shorta",a:28,ca:15},{n:"M. Ali",c:"Al Quwa",a:26,ca:10},{n:"H. Tarnin",c:"Al Zawraa",a:28,ca:8},{n:"M. Kadem",c:"Al Shorta",a:28,ca:10},{n:"N. Ghanim",c:"Al Zawraa",a:25,ca:3},{n:"K. Al-Amir",c:"Al Quwa",a:27,ca:5}],mf:[{n:"O. Raed",c:"Al Quwa",a:23,ca:10},{n:"A. Attwan",c:"Al Shorta",a:30,ca:25},{n:"I. Bayesh",c:"Al Quwa",a:25,ca:15},{n:"H. Abdulkareem",c:"Al Zawraa",a:26,ca:10},{n:"Y. Ammar",c:"Al Shorta",a:24,ca:5},{n:"R. Qasim",c:"Al Zawraa",a:24,ca:3},{n:"M. Majid",c:"Al Quwa",a:26,ca:8},{n:"A. Mohsin",c:"Al Zawraa",a:25,ca:5}],fw:[{n:"M. Mohanad",c:"Al Quwa",a:28,ca:20},{n:"A. Hussein",c:"Al Shorta",a:26,ca:15},{n:"H. Aamer",c:"Al Zawraa",a:25,ca:5},{n:"K. Tariq",c:"Al Quwa",a:25,ca:3},{n:"Y. Abdul",c:"Al Shorta",a:24,ca:2},{n:"S. Jasim",c:"Al Zawraa",a:26,ca:4}]};
teamsData["Noruega"] = {gk:[{n:"Ø. Nyland",c:"RB Leipzig",a:34,ca:50},{n:"M. Dyngeland",c:"Brann",a:29,ca:5},{n:"E. Selvik",c:"Haugesund",a:25,ca:3}],df:[{n:"J. Ryerson",c:"Dortmund",a:27,ca:25},{n:"A. Hanche-Olsen",c:"Mainz",a:28,ca:25},{n:"L. Østigård",c:"Napoli",a:25,ca:20},{n:"F. Aursnes",c:"Benfica",a:29,ca:25},{n:"D. Wolfe",c:"Brommapojkarna",a:28,ca:10},{n:"M. Thorsby",c:"Genoa",a:29,ca:25},{n:"C. Pedersen",c:"Fenerbahçe",a:30,ca:20},{n:"J. Svensson",c:"AZ",a:31,ca:15}],mf:[{n:"M. Ødegaard",c:"Arsenal",a:26,ca:60},{n:"S. Berge",c:"Burnley",a:27,ca:45},{n:"H. Ajer",c:"Brentford",a:27,ca:20},{n:"K. Thorsby",c:"Genoa",a:29,ca:25},{n:"M. Jensen",c:"Brann",a:24,ca:5},{n:"O. Solbakken",c:"Roma",a:26,ca:15},{n:"J. Kitolano",c:"Twente",a:25,ca:5},{n:"E. Botheim",c:"Salernitana",a:25,ca:5}],fw:[{n:"E. Haaland",c:"Man City",a:25,ca:40},{n:"A. Sørloth",c:"Atlético",a:29,ca:55},{n:"J. Larsen",c:"Celta",a:26,ca:10},{n:"O. Bobb",c:"Man City",a:21,ca:5},{n:"J. Strand Larsen",c:"Celta",a:25,ca:10},{n:"T. Heggem",c:"Brann",a:24,ca:3}]};
teamsData["Senegal"] = {gk:[{n:"É. Mendy",c:"Al Hilal",a:33,ca:40},{n:"S. Dieng",c:"Middlesbrough",a:30,ca:5},{n:"B. Gomis",c:"Dauphine",a:26,ca:3}],df:[{n:"K. Koulibaly",c:"Al Hilal",a:34,ca:80},{n:"A. Diallo",c:"PSG",a:31,ca:15},{n:"I. Jakobs",c:"Monaco",a:25,ca:15},{n:"M. Niakhate",c:"Lyon",a:29,ca:25},{n:"F. Mendy",c:"Lyon",a:30,ca:10},{n:"A. Seck",c:"Maccabi Haifa",a:32,ca:15},{n:"A. Ciss",c:"Lyon",a:27,ca:10},{n:"N. Badiane",c:"Génération Foot",a:25,ca:3}],mf:[{n:"I. Gueye",c:"Marseille",a:35,ca:65},{n:"N. Mendy",c:"Lens",a:33,ca:30},{n:"P. Sarr",c:"Tottenham",a:25,ca:20},{n:"K. Diatta",c:"Monaco",a:26,ca:35},{n:"L. Ciss",c:"Rennes",a:28,ca:10},{n:"M. Camara",c:"Monaco",a:27,ca:15},{n:"D. Diop",c:"Lorient",a:24,ca:5},{n:"B. Dieng",c:"Angers",a:25,ca:3}],fw:[{n:"S. Mané",c:"Al Nassr",a:33,ca:110},{n:"N. Jackson",c:"Chelsea",a:24,ca:15},{n:"I. Sarr",c:"Marseille",a:33,ca:55},{n:"H. Diallo",c:"Rangers",a:26,ca:30},{n:"M. Bamba",c:"Lorient",a:24,ca:5},{n:"A. Dieng",c:"Lorient",a:26,ca:10}]};

// J
teamsData["Argelia"] = {gk:[{n:"A. Mandrea",c:"Angers",a:34,ca:15},{n:"M. Guendouz",c:"CR Belouizdad",a:26,ca:5},{n:"O. Benbot",c:"JS Kabylie",a:27,ca:3}],df:[{n:"R. Atal",c:"Genk",a:29,ca:35},{n:"A. Mandi",c:"Villarreal",a:33,ca:80},{n:"R. Bensebaini",c:"Dortmund",a:30,ca:55},{n:"M. Ammari",c:"CR Belouizdad",a:27,ca:5},{n:"K. Ait-Nouri",c:"Wolves",a:24,ca:15},{n:"M. Tougai",c:"ES Tunis",a:26,ca:10},{n:"Y. Guitane",c:"Le Havre",a:25,ca:5},{n:"A. Abdelli",c:"Angers",a:26,ca:10}],mf:[{n:"R. Mahrez",c:"Al Ahli",a:34,ca:95},{n:"I. Bennacer",c:"AC Milan",a:27,ca:45},{n:"H. Feghouli",c:"Galatasaray",a:35,ca:80},{n:"A. Zerrouki",c:"Feyenoord",a:26,ca:20},{n:"F. Bentaleb",c:"Lille",a:30,ca:50},{n:"Y. Belaili",c:"MC Alger",a:33,ca:55},{n:"A. Ounas",c:"Lille",a:28,ca:25},{n:"I. Hadj Moussa",c:"Feyenoord",a:23,ca:5}],fw:[{n:"I. Slimani",c:"CR Belouizdad",a:37,ca:90},{n:"A. Amoura",c:"Wolfsburg",a:25,ca:20},{n:"B. Bounedjah",c:"Al Ahli",a:33,ca:65},{n:"M. Gouiri",c:"Rennes",a:27,ca:15},{n:"R. Delort",c:"MC Alger",a:34,ca:30},{n:"I. Slimani",c:"CR Belouizdad",a:37,ca:90}]};
teamsData["Argentina"] = {gk:[{n:"E. Martínez",c:"Aston Villa",a:33,ca:50},{n:"F. Armani",c:"River Plate",a:38,ca:20},{n:"G. Rulli",c:"Marseille",a:33,ca:5}],df:[{n:"N. Molina",c:"Atlético Madrid",a:27,ca:40},{n:"C. Romero",c:"Tottenham",a:27,ca:30},{n:"N. Otamendi",c:"Benfica",a:37,ca:115},{n:"G. Montiel",c:"Sevilla",a:28,ca:25},{n:"L. Martínez",c:"Man Utd",a:27,ca:25},{n:"M. Acuña",c:"Racing",a:33,ca:60},{n:"N. Tagliafico",c:"Lyon",a:32,ca:60},{n:"J. Foyth",c:"Villarreal",a:27,ca:20}],mf:[{n:"L. Messi",c:"Inter Miami",a:38,ca:190},{n:"L. Paredes",c:"Roma",a:31,ca:60},{n:"R. De Paul",c:"Atlético Madrid",a:31,ca:65},{n:"E. Fernández",c:"Chelsea",a:24,ca:25},{n:"A. Mac Allister",c:"Liverpool",a:26,ca:30},{n:"E. Palacios",c:"Bayer Leverkusen",a:26,ca:10},{n:"G. Lo Celso",c:"Betis",a:29,ca:45},{n:"N. Paz",c:"Como",a:21,ca:5}],fw:[{n:"J. Álvarez",c:"Atlético Madrid",a:25,ca:40},{n:"L. Martínez",c:"Inter",a:27,ca:65},{n:"Á. Di María",c:"Benfica",a:37,ca:145},{n:"J. Correa",c:"Atlético Madrid",a:30,ca:15},{n:"A. Garnacho",c:"Man Utd",a:21,ca:10},{n:"N. González",c:"Juventus",a:27,ca:20}]};
teamsData["Austria"] = {gk:[{n:"A. Schlager",c:"RB Leipzig",a:29,ca:15},{n:"P. Pentz",c:"Brøndby",a:28,ca:5},{n:"N. Hedl",c:"Rapid Viena",a:24,ca:3}],df:[{n:"D. Alaba",c:"Real Madrid",a:33,ca:110},{n:"S. Posch",c:"Bologna",a:28,ca:20},{n:"P. Lienhart",c:"Freiburg",a:29,ca:20},{n:"G. Trauner",c:"Feyenoord",a:33,ca:15},{n:"M. Wöber",c:"Leeds",a:27,ca:15},{n:"K. Danso",c:"Tottenham",a:26,ca:25},{n:"A. Prass",c:"Hoffenheim",a:24,ca:5},{n:"F. Ulmer",c:"Salzburg",a:39,ca:30}],mf:[{n:"M. Sabitzer",c:"Dortmund",a:31,ca:80},{n:"X. Schlager",c:"RB Leipzig",a:27,ca:40},{n:"K. Laimer",c:"Bayern",a:28,ca:40},{n:"F. Grillitsch",c:"Hoffenheim",a:30,ca:35},{n:"C. Baumgartner",c:"RB Leipzig",a:25,ca:40},{n:"R. Sallinger",c:"Salzburg",a:28,ca:5},{n:"A. Weimann",c:"Bristol City",a:33,ca:25},{n:"M. Gregoritsch",c:"Freiburg",a:31,ca:60}],fw:[{n:"M. Arnautović",c:"Inter",a:36,ca:115},{n:"K. Stöger",c:"Bochum",a:29,ca:5},{n:"S. Horvath",c:"Salzburg",a:25,ca:5},{n:"M. Demir",c:"Salzburg",a:22,ca:5},{n:"A. Schmid",c:"Salzburg",a:25,ca:3},{n:"T. Sabitzer",c:"Salzburg",a:24,ca:2}]};
teamsData["Jordania"] = {gk:[{n:"Y. Abu Layla",c:"Al Faisaly",a:31,ca:30},{n:"A. Al-Fakhouri",c:"Al Wehdat",a:30,ca:10},{n:"M. Al-Emam",c:"Al Faisaly",a:26,ca:5}],df:[{n:"E. Al-Ajalin",c:"Al Wehdat",a:27,ca:15},{n:"A. Al Tamimi",c:"Al Faisaly",a:28,ca:10},{n:"B. Al-Manasrah",c:"Al Faisaly",a:26,ca:8},{n:"M. Al-Awawdeh",c:"Al Wehdat",a:28,ca:10},{n:"S. Al-Rousan",c:"Al Faisaly",a:25,ca:5},{n:"A. Haddad",c:"Al Faisaly",a:26,ca:5},{n:"Y. Al-Rawashdeh",c:"Al Wehdat",a:27,ca:3}],mf:[{n:"N. Al-Rawabdeh",c:"Al Faisaly",a:28,ca:15},{n:"M. Abu Zrait",c:"Al Wehdat",a:26,ca:10},{n:"S. Al-Naimat",c:"Al Ahli",a:27,ca:15},{n:"A. Al-Mardi",c:"Al Faisaly",a:25,ca:8},{n:"I. Al-Haj",c:"Al Faisaly",a:26,ca:5},{n:"O. Hani",c:"Al Wehdat",a:25,ca:5},{n:"R. Al-Dawud",c:"Al Faisaly",a:25,ca:3}],fw:[{n:"M. Al-Taamari",c:"Montpellier",a:28,ca:25},{n:"O. Al-Naimat",c:"Al Ahli",a:27,ca:15},{n:"Y. Al-Rawashdeh",c:"Al Wehdat",a:26,ca:5},{n:"A. Al-Sheyab",c:"Al Faisaly",a:24,ca:3},{n:"H. Al-Fayez",c:"Al Faisaly",a:25,ca:2},{n:"B. Al-Haj",c:"Al Faisaly",a:24,ca:2}]};

// K
teamsData["Colombia"] = {gk:[{n:"C. Vargas",c:"Atlas",a:36,ca:25},{n:"K. Mier",c:"Dep. Cali",a:27,ca:5},{n:"Á. Montero",c:"Millonarios",a:26,ca:3}],df:[{n:"D. Sánchez",c:"Galatasaray",a:29,ca:55},{n:"Y. Mosquera",c:"Wolves",a:23,ca:10},{n:"J. Mojica",c:"Villarreal",a:32,ca:30},{n:"C. Cuesta",c:"Genk",a:26,ca:15},{n:"S. Arias",c:"Bahia",a:33,ca:55},{n:"W. Barrios",c:"Boca Juniors",a:31,ca:15},{n:"A. Muñoz",c:"Crystal Palace",a:25,ca:10},{n:"J. Cuesta",c:"Lens",a:24,ca:5}],mf:[{n:"J. Rodríguez",c:"Junior",a:34,ca:90},{n:"M. Uribe",c:"Al Sadd",a:34,ca:55},{n:"K. Castaño",c:"Racing",a:25,ca:10},{n:"J. Arias",c:"Fluminense",a:27,ca:15},{n:"D. Zapata",c:"América-MG",a:34,ca:35},{n:"Y. Asprilla",c:"Girona",a:21,ca:8},{n:"Í. Carbonero",c:"Racing",a:24,ca:5},{n:"G. Lerma",c:"Crystal Palace",a:30,ca:45}],fw:[{n:"L. Díaz",c:"Liverpool",a:28,ca:55},{n:"R. Borré",c:"Inter",a:29,ca:30},{n:"J. Durán",c:"Aston Villa",a:21,ca:10},{n:"M. Moreno",c:"Ind. Medellín",a:27,ca:10},{n:"S. Córdoba",c:"Vizela",a:27,ca:5},{n:"H. Preciado",c:"Santos",a:26,ca:5}]};
teamsData["RD Congo"] = {gk:[{n:"L. Mpasi",c:"Al Taawoun",a:31,ca:15},{n:"D. Nlandu",c:"TP Mazembe",a:28,ca:5},{n:"B. Luyeye",c:"Vita Club",a:26,ca:3}],df:[{n:"C. M. Samba",c:"Rennes",a:32,ca:20},{n:"A. Masuaku",c:"Beşiktaş",a:31,ca:20},{n:"D. Batubinsika",c:"Antwerp",a:29,ca:10},{n:"R. Muzinga",c:"TP Mazembe",a:27,ca:10},{n:"J. Kalombo",c:"TP Mazembe",a:26,ca:5},{n:"N. Bafuidi",c:"Vita Club",a:27,ca:5},{n:"A. Chongo",c:"TP Mazembe",a:25,ca:3}],mf:[{n:"S. Moutoussamy",c:"Sivasspor",a:28,ca:25},{n:"A. Kakuta",c:"Amiens",a:34,ca:25},{n:"C. Bongonda",c:"Spartak Moscú",a:29,ca:20},{n:"G. Elia",c:"Rennes",a:27,ca:15},{n:"O. Nkama",c:"TP Mazembe",a:26,ca:5},{n:"M. Ngoie",c:"TP Mazembe",a:25,ca:3},{n:"P. Moke",c:"Vita Club",a:27,ca:5}],fw:[{n:"C. Bakambu",c:"Real Betis",a:34,ca:50},{n:"Y. Wissa",c:"Brentford",a:28,ca:20},{n:"S. Banza",c:"Braga",a:30,ca:25},{n:"F. Mayele",c:"Young Africans",a:29,ca:10},{n:"J. Malango",c:"Raja Casablanca",a:31,ca:10},{n:"M. Mondongo",c:"TP Mazembe",a:25,ca:3}]};
teamsData["Portugal"] = {gk:[{n:"D. Costa",c:"Porto",a:25,ca:30},{n:"J. Sá",c:"Wolves",a:32,ca:5},{n:"R. Patrício",c:"Roma",a:37,ca:110}],df:[{n:"R. Dias",c:"Man City",a:28,ca:55},{n:"N. Mendes",c:"PSG",a:23,ca:20},{n:"D. Dalot",c:"Man Utd",a:26,ca:20},{n:"G. Inácio",c:"Sporting",a:23,ca:10},{n:"J. Cancelo",c:"Barcelona",a:31,ca:50},{n:"N. Tavares",c:"Lazio",a:25,ca:5},{n:"A. Silva",c:"Benfica",a:21,ca:8},{n:"Pepe",c:"FC Porto",a:42,ca:130}],mf:[{n:"B. Fernandes",c:"Man Utd",a:30,ca:70},{n:"João Neves",c:"PSG",a:21,ca:10},{n:"Otávio",c:"Al Nassr",a:30,ca:20},{n:"R. Neves",c:"Al Hilal",a:28,ca:40},{n:"Matheus N.",c:"Man Utd",a:26,ca:10},{n:"Vitinha",c:"PSG",a:25,ca:20},{n:"P. Gonçalves",c:"Sporting",a:27,ca:15},{n:"J. Palhinha",c:"Bayern",a:30,ca:25}],fw:[{n:"C. Ronaldo",c:"Al Nassr",a:40,ca:220},{n:"Diogo Jota",c:"Liverpool",a:28,ca:40},{n:"R. Leão",c:"AC Milan",a:26,ca:35},{n:"Bernardo Silva",c:"Man City",a:30,ca:95},{n:"G. Ramos",c:"PSG",a:24,ca:15},{n:"Francisco C.",c:"Benfica",a:24,ca:10}]};
teamsData["Uzbekistán"] = {gk:[{n:"O. Nematov",c:"Pakhtakor",a:31,ca:20},{n:"A. Yusupov",c:"Navbahor",a:28,ca:10},{n:"K. Rakhimov",c:"Pakhtakor",a:27,ca:5}],df:[{n:"R. Ashurmatov",c:"Rubin Kazán",a:29,ca:35},{n:"K. Alijonov",c:"Pakhtakor",a:28,ca:20},{n:"U. Eshmurodov",c:"Lokomotiv",a:31,ca:25},{n:"A. Kobilov",c:"Pakhtakor",a:27,ca:15},{n:"D. Khamdamov",c:"Navbahor",a:28,ca:10},{n:"M. Saitov",c:"Pakhtakor",a:26,ca:5},{n:"J. Yoqubjon",c:"Pakhtakor",a:25,ca:3}],mf:[{n:"O. Shukurov",c:"Qayrat",a:29,ca:30},{n:"J. Masharipov",c:"Al Nassr",a:30,ca:40},{n:"O. Khamrobekov",c:"Pakhtakor",a:27,ca:10},{n:"A. Fayzullaev",c:"CSKA Moscú",a:22,ca:10},{n:"S. Abdurahmanov",c:"Pakhtakor",a:26,ca:5},{n:"K. Mukhiddinov",c:"Pakhtakor",a:25,ca:3},{n:"A. Giyosov",c:"Nasaf",a:26,ca:5}],fw:[{n:"E. Shomurodov",c:"Roma",a:30,ca:75},{n:"N. Khamdamov",c:"Navbahor",a:28,ca:15},{n:"T. Abdusalomov",c:"Pakhtakor",a:25,ca:5},{n:"B. Nasimov",c:"Nasaf",a:26,ca:10},{n:"S. Erkinov",c:"Pakhtakor",a:24,ca:3},{n:"A. Norchaev",c:"Nasaf",a:25,ca:2}]};

// L
teamsData["Croacia"] = {gk:[{n:"D. Livaković",c:"Fenerbahçe",a:30,ca:60},{n:"I. Ivušić",c:"Pafos",a:30,ca:5},{n:"N. Labrović",c:"Augsburg",a:26,ca:3}],df:[{n:"J. Gvardiol",c:"Man City",a:23,ca:35},{n:"D. Vida",c:"AEK",a:36,ca:105},{n:"J. Šutalo",c:"Ajax",a:25,ca:15},{n:"B. Sosa",c:"Torino",a:27,ca:20},{n:"M. Erlić",c:"Bologna",a:27,ca:10},{n:"J. Stanišić",c:"Bayern",a:24,ca:10},{n:"M. Baturina",c:"Dinamo Zagreb",a:22,ca:5},{n:"D. Perišić",c:"Tottenham",a:36,ca:130}],mf:[{n:"L. Modrić",c:"Real Madrid",a:39,ca:180},{n:"M. Brozović",c:"Al Nassr",a:32,ca:100},{n:"M. Kovačić",c:"Man City",a:31,ca:100},{n:"M. Pašalić",c:"Atalanta",a:30,ca:65},{n:"N. Vlašić",c:"Torino",a:27,ca:55},{n:"L. Ivanušec",c:"Feyenoord",a:26,ca:20},{n:"P. Sučić",c:"Dinamo Zagreb",a:22,ca:8},{n:"M. Livaja",c:"Hajduk",a:32,ca:25}],fw:[{n:"A. Kramarić",c:"Hoffenheim",a:34,ca:100},{n:"B. Petković",c:"Dinamo Zagreb",a:30,ca:40},{n:"I. Perišić",c:"Tottenham",a:36,ca:130},{n:"M. Oršić",c:"Southampton",a:32,ca:40},{n:"F. Budimir",c:"Osasuna",a:33,ca:15},{n:"L. Suma",c:"HNK Gorica",a:25,ca:5}]};
teamsData["Inglaterra"] = {gk:[{n:"J. Pickford",c:"Everton",a:31,ca:70},{n:"D. Henderson",c:"Crystal Palace",a:32,ca:5},{n:"A. Ramsdale",c:"Southampton",a:27,ca:5}],df:[{n:"K. Walker",c:"AC Milan",a:35,ca:85},{n:"J. Stones",c:"Man City",a:31,ca:80},{n:"H. Maguire",c:"Man Utd",a:32,ca:65},{n:"L. Shaw",c:"Man Utd",a:30,ca:35},{n:"R. James",c:"Chelsea",a:25,ca:20},{n:"M. Guehi",c:"Crystal Palace",a:25,ca:20},{n:"B. Chilwell",c:"Chelsea",a:28,ca:25},{n:"E. Konsa",c:"Aston Villa",a:27,ca:10}],mf:[{n:"D. Rice",c:"Arsenal",a:26,ca:60},{n:"J. Bellingham",c:"Real Madrid",a:22,ca:40},{n:"P. Foden",c:"Man City",a:25,ca:45},{n:"C. Gallagher",c:"Atlético Madrid",a:25,ca:20},{n:"C. Palmer",c:"Chelsea",a:23,ca:15},{n:"J. Maddison",c:"Tottenham",a:28,ca:10},{n:"K. Mainoo",c:"Man Utd",a:20,ca:8},{n:"E. Anderson",c:"Nottingham",a:22,ca:3}],fw:[{n:"H. Kane",c:"Bayern",a:32,ca:105},{n:"B. Saka",c:"Arsenal",a:23,ca:45},{n:"M. Rashford",c:"Aston Villa",a:27,ca:60},{n:"O. Watkins",c:"Aston Villa",a:29,ca:15},{n:"A. Gordon",c:"Newcastle",a:24,ca:10},{n:"J. Bowen",c:"West Ham",a:28,ca:10}]};
teamsData["Ghana"] = {gk:[{n:"L. Ati-Zigi",c:"St. Gallen",a:30,ca:15},{n:"J. Wollacott",c:"Hibernian",a:28,ca:10},{n:"P. Mensah",c:"Hearts of Oak",a:26,ca:5}],df:[{n:"A. Djiku",c:"Fenerbahçe",a:30,ca:30},{n:"M. Salisu",c:"Monaco",a:26,ca:20},{n:"G. Mensah",c:"Bordeaux",a:32,ca:25},{n:"T. Lamptey",c:"Brighton",a:24,ca:10},{n:"D. Opare",c:"Almería",a:28,ca:15},{n:"A. Nurudeen",c:"Eupen",a:26,ca:5},{n:"J. Mensah",c:"Hearts of Oak",a:25,ca:3},{n:"D. Amos",c:"Hearts of Oak",a:26,ca:3}],mf:[{n:"T. Partey",c:"Arsenal",a:32,ca:50},{n:"M. Kudus",c:"West Ham",a:25,ca:30},{n:"I. Afena-Gyan",c:"Cremonese",a:22,ca:5},{n:"E. Owusu",c:"Dortmund",a:23,ca:5},{n:"K. Sulemana",c:"Southampton",a:23,ca:10},{n:"S. Abdulai",c:"Hearts of Oak",a:26,ca:5},{n:"F. Antwi",c:"Hearts of Oak",a:25,ca:3},{n:"S. Nketiah",c:"Hearts of Oak",a:24,ca:2}],fw:[{n:"A. Ayew",c:"Le Havre",a:35,ca:120},{n:"J. Ayew",c:"Leicester",a:33,ca:110},{n:"E. Boateng",c:"Nottingham",a:30,ca:15},{n:"I. Williams",c:"Athletic",a:23,ca:10},{n:"O. Addo",c:"Hearts of Oak",a:25,ca:3},{n:"R. Opoku",c:"Hearts of Oak",a:24,ca:2}]};
teamsData["Panamá"] = {gk:[{n:"O. Mosquera",c:"Universitario",a:32,ca:5},{n:"C. Samudio",c:"Ind. La Chorrera",a:28,ca:5},{n:"E. Hughes",c:"Tauro",a:26,ca:3}],df:[{n:"M. Murillo",c:"Olympiacos",a:29,ca:25},{n:"J. Escobar",c:"Deportivo Cali",a:29,ca:15},{n:"E. Davis",c:"Alajuelense",a:34,ca:60},{n:"A. Palacios",c:"Costa del Este",a:27,ca:10},{n:"I. Anderson",c:"Alajuelense",a:28,ca:10},{n:"R. Perdomo",c:"Tauro",a:26,ca:5},{n:"J. Góndola",c:"Tauro",a:27,ca:5}],mf:[{n:"A. Godoy",c:"Nashville",a:35,ca:70},{n:"J. Rodríguez",c:"Costa del Este",a:27,ca:15},{n:"C. Martínez",c:"Ind. La Chorrera",a:25,ca:8},{n:"F. Góndola",c:"Tauro",a:26,ca:5},{n:"E. Rodríguez",c:"Costa del Este",a:26,ca:5},{n:"M. Ayarza",c:"Tauro",a:25,ca:3},{n:"K. Mosquera",c:"Tauro",a:25,ca:2}],fw:[{n:"I. Díaz",c:"U Católica",a:28,ca:10},{n:"J. Fajardo",c:"Costa del Este",a:32,ca:30},{n:"E. Bárcenas",c:"Toluca",a:31,ca:40},{n:"C. Small",c:"Ind. La Chorrera",a:27,ca:10},{n:"A. Tejada",c:"Tauro",a:27,ca:10},{n:"O. McKenzie",c:"Tauro",a:26,ca:5}]};

const existingTeams = existing.map(t => t.team);

// Build all teams ordered by groups
const orderedTeams = [];
for (const [group, teams] of Object.entries(groups)) {
  for (const team of teams) {
    if (existingTeams.includes(team)) {
      const found = existing.find(t => t.team === team);
      orderedTeams.push(found);
    } else {
      const raw = teamsData[team];
      if (!raw) { console.log("MISSING: " + team); continue; }
      const players = normalizePlayers(raw);
      orderedTeams.push({
        team: team,
        coach: coaches[team] || "Por definir",
        formation: "4-3-3",
        players: players
      });
    }
  }
}

fs.writeFileSync('/home/user/pollamundial2026/pollaworld-2026/server/src/db/squads.json', JSON.stringify(orderedTeams, null, 2));
console.log(`Written ${orderedTeams.length} teams`);
orderedTeams.forEach((t, i) => console.log(`${i+1}. ${t.team}: ${t.players.length} players`));
